### ISSUE TITLE
Multiple nginx vhosts

### ISSUE THREAD

**Issue by jorgedferreira** [zecure/shadowd_php#61]
Hi, first of all, great software you have built! Congrats!

I have a question though, I'm trying to create multiple profiles, one for each vhost, but cant seem to understand how can i configure the connector to use the correct profile. I've read in your docs that it is possible to use SHADOWD_CONNECTOR_CONFIG, but how does one set that ENV flag per domain/nginx vhost?

Thanks again for the software and for your time!

Best regards

**Comment by zit-hb** [comment]
Hey Jorge,

Thanks a lot!

It depends on your setup. Can you share your Nginx config?

**Comment by jorgedferreira** [comment]
Hey, speedy reply, didn't expect that, what another pleasant surprise.

Well, we don't use any management panel, so we have for each vhost a file with its configuration, I'm pasting bellow and example:

`
server {
	listen 80;

	charset utf-8;
	root /home/user/Sites/demo_stuff/;

  access_log  /var/log/nginx/demo_access.log;
  error_log   /var/log/nginx/demo_error.log;

	index index.php index.html;

	server_name demo.local;

	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

	location ~ \.php$ {
		fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/php/shadowd.php";

		try_files $uri /index.php?$query_string;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		fastcgi_pass unix:/run/php/php7.2-fpm.sock;
		fastcgi_read_timeout 300;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}

	include /usr/share/nginx/confs/drop.conf;
	include /usr/share/nginx/confs/compression.conf;
	include /usr/share/nginx/confs/services.conf;
	include /usr/share/nginx/confs/caching.conf;
	
	add_header 'Access-Control-Allow-Origin' '*';
	add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
	add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
}
`

**Comment by jorgedferreira** [comment]
Oh, is it with fastcgi_param SHADOWD_CONNECTOR_CONFIG abc123;  ? 
Update: seems not, i added fastcgi_param SHADOWD_CONNECTOR_CONFIG "lkajhakjhaklajh"; refering to a second profile but i get error of required file missing.

Also, for whats i see in /etc/shadowd/connectors.ini, since i provide the profile id there, i would think i needed to provide that id also as an env. variable, not just the key...

**Comment by jorgedferreira** [comment]
I came back to this and read the code and noticed my mistake. I Was passing the key, and it is a connector.ini (or a section)

    fastcgi_param SHADOWD_CONNECTOR_CONFIG "/etc/shadowd/site2_connector.ini";
    fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/php/shadowd.php";

But now i get an error when calling the domain root:

Too long parameter path

#0 /usr/share/shadowd/php/src/Connection.php(74): shadowd\Connection->parseOutputData('{"message":"Too...')
#1 /usr/share/shadowd/php/src/Connector.php(54): shadowd\Connection->send(Object(shadowd\Input))
#2 /usr/share/shadowd/php/shadowd.php(26): shadowd\Connector->start()
#3 {main}

**Comment by zit-hb** [comment]
> ```
> fastcgi_param SHADOWD_CONNECTOR_CONFIG "/etc/shadowd/site2_connector.ini";
> fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/php/shadowd.php";
> ```

Yea, this looks right.

The error message is unrelated to that. It is thrown [here](https://github.com/zecure/shadowd/blob/v2.2.0/src/connection.cpp#L251). The [default value](https://github.com/zecure/shadowd/blob/v2.2.0/src/config.cpp#L71) for max. parameter length is 64, so it seems  there is a parameter in your request that has a longer name? Is that a possibility for some reason?

Please try to increase the value by adding `--max-length-path` to a custom command of [shadowd in shadowdctl](https://github.com/zecure/shadowdctl/blob/v2.0.0/docker-compose.yml#L40). Don't forget to restart with `down` and `up`.

**Comment by jorgedferreira** [comment]
Good morning! Well, that strange because i was just calling the home page. It did not have any parameter, but it does make a redirect to another page adding /en/ to the main url...

Either way, thanks for the reply. It's working with those settings.

I'm testing this problem about the parameter length (now it doesn't happen).

Best regards,

**Comment by zit-hb** [comment]
Great to hear that it worked!

In Shadow Daemon HTTP headers that are sent by the client are also considered parameters. But normally browsers should not be sending HTTP headers whose key is more than 64 characters long.

**Comment by jorgedferreira** [comment]
Hi. Sorry for the late reply. I've since set the parameters but i've noticed another thing.

Although i just added the fastcgi_param (config and auto_prepend_file) to a single Vhost, it affects all the PHP-FPM pool right? Because if i have multiple sites on the same pool (default on may dev machine) and i get errors from other vhosts...

So, i need to have a pool for each vhost to isolate  shadowd? I find it strange, because i only apply shadowd to one vhost in the php location...

**Comment by zit-hb** [comment]
Hey, I will try to have a look on the next weekend. I am unfortunately very busy the next days and I haven't used NGiNX for some years.

**Comment by jorgedferreira** [comment]
Hi! Ok, so I have a little more information on this, sorry for the long reply but maybe it helps other people.

Since PHP-FPM spawns multiple child processes to handle the requests, on an one pool FPM config, all the threads/childs will deal with every request they get from NGINX. 

If it's multiple vhosts on the same pool it can happen (often quickly) that **a PHP-FPM child that did some previous work** for nginx on a Shadowd enabled vhost **will keep the parameters** for his lifetime, in this case auto_prepend_file and will maintain that parameter for the next requests, and then when it hits a non-enabled vhost/profile, **we get the missing configuration or missing file** error. This might happen immediately or after a little while after using both vhosts (enabled and non-enabled)

Tests i've run:
- Using the parameters on nginx vhost, location PHP, with one (1) PHP-FPM pool:
(first vhost)
fastcgi_param SHADOWD_CONNECTOR_CONFIG "/etc/shadowd/site1_connector.ini"; 
fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/php/shadowd.php"; 
This setting **generates errors** on neighbor vhosts using the same php-fpm processes that do not use Shadowd.

- Using the parameters on multiple nginx vhosts, location PHP, with one (1) PHP-FPM pool:
(first vhost)
fastcgi_param SHADOWD_CONNECTOR_CONFIG "/etc/shadowd/site1_connector.ini"; 
fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/php/shadowd.php"; 
(second vhost)
fastcgi_param SHADOWD_CONNECTOR_CONFIG "/etc/shadowd/site2_connector.ini"; 
fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/php/shadowd.php"; 
This works and gets over the missing file, **but requires all vhosts to have shadowd enabled and configured correctly**.

- Using multiple PHP-FPM pools **works**, since there is isolation on the workload of the child processes but the resources used will be greatly increased and longer configuration time will be required to tailor the pools to the optimal settings per vhost for better usage of cpu/ram. This IS the best and safest way to run things if you can spare the resources.

The best configuration I've gotten was a mix of settings. 

1. On nginx VHOST i've added **ONLY the connector config param**, fastcgi_param SHADOWD_CONNECTOR_CONFIG "/etc/shadowd/site1_connector.ini"; 
2. On PHP-FPM php.ini file I'm adding a section for that particular HOST to prepend the file. For example, lets say I want to secure site1.com. In php.ini I'll add:
[HOST=site1.com]
auto_prepend_file="/usr/share/shadowd/php/shadowd.php"

(be aware that in order to use HOST= we have to use the first server_name value on the NGINX vhost. If we have something like server_name=site1.com www.site1.com then we should use site1.com because thats whats sent to PHP-FPM by nginx)

This way, I have only one PHP-FPM pool but the auto_prepend_file only happens for that site1.

If one needs to add more vhosts, add the env variable SHADOWD_CONNECTOR_CONFIG on the nginx vhost (location php) and enable the usage of Shadowd on FPM's php.ini with another HOST section.

Well, best regards and thanks again for the software and your time!

**Comment by zit-hb** [comment]
Hey Jorge,

Thanks for the detailed investigation! That is interesting, I was not aware of this limitations. I have some other ideas how this could possibly be solved but it will require changes to the connector code, so it will take a bit.

**Comment by jorgedferreira** [comment]
Hi. Yeah, you probably can check the request source on the connector and see if it's a active profile.

For now, at least for me it's solved.

Best regards, have a good weekend
